=begin
#gateway_timesheets API

#gateway_timesheets API documentation

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::UserjwtcontrollerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserjwtcontrollerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::UserjwtcontrollerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserjwtcontrollerApi' do
    it 'should create an instance of UserjwtcontrollerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::UserjwtcontrollerApi)
    end
  end

  # unit tests for authorize_using_post
  # authorize
  # 
  # @param login_vm loginVM
  # @param [Hash] opts the optional parameters
  # @return [JWTToken]
  describe 'authorize_using_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
