=begin
#gateway_timesheets API

#gateway_timesheets API documentation

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ProfileInfoVM
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProfileInfoVM' do
  before do
    # run before each test
    @instance = SwaggerClient::ProfileInfoVM.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProfileInfoVM' do
    it 'should create an instance of ProfileInfoVM' do
      expect(@instance).to be_instance_of(SwaggerClient::ProfileInfoVM)
    end
  end
  describe 'test attribute "active_profiles"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "ribbon_env"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

