=begin
#timesheets API

#timesheets API documentation

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/login_vm'
require 'swagger_client/models/jwt_token'
require 'swagger_client/models/user'
require 'swagger_client/models/projects'
require 'swagger_client/models/key_and_password_vm'
require 'swagger_client/models/managed_user_vm'
require 'swagger_client/models/profile_info_vm'
require 'swagger_client/models/route_vm'
require 'swagger_client/models/service_instance'
require 'swagger_client/models/uri'
require 'swagger_client/models/user_dto'

# APIs
require 'swagger_client/api/profileinforesource_api'
require 'swagger_client/api/projectsresource_api'
require 'swagger_client/api/userjwtcontroller_api'
require 'swagger_client/api/accountresource_api'
require 'swagger_client/api/gatewayresource_api'
require 'swagger_client/api/userresource_api'



module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
