=begin
#timesheets API

#timesheets API documentation

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require "uri"

module SwaggerClient
  class ProjectsresourceApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # createProjects
    # 
    # @param projects projects
    # @param [Hash] opts the optional parameters
    # @return [Projects]
    def create_projects_using_post(projects, opts = {})
      data, _status_code, _headers = create_projects_using_post_with_http_info(projects, opts)
      return data
    end

    # createProjects
    # 
    # @param projects projects
    # @param [Hash] opts the optional parameters
    # @return [Array<(Projects, Fixnum, Hash)>] Projects data, response status code and response headers
    def create_projects_using_post_with_http_info(projects, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: ProjectsresourceApi.create_projects_using_post ..."
      end
      # verify the required parameter 'projects' is set
      if @api_client.config.client_side_validation && projects.nil?
        fail ArgumentError, "Missing the required parameter 'projects' when calling ProjectsresourceApi.create_projects_using_post"
      end
      # resource path
      local_var_path = "/api/projects"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(projects)
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Projects')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ProjectsresourceApi#create_projects_using_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # deleteProjects
    # 
    # @param id id
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def delete_projects_using_delete(id, opts = {})
      delete_projects_using_delete_with_http_info(id, opts)
      return nil
    end

    # deleteProjects
    # 
    # @param id id
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def delete_projects_using_delete_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: ProjectsresourceApi.delete_projects_using_delete ..."
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling ProjectsresourceApi.delete_projects_using_delete"
      end
      # resource path
      local_var_path = "/api/projects/{id}".sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ProjectsresourceApi#delete_projects_using_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # getAllProjects
    # 
    # @param [Hash] opts the optional parameters
    # @return [Array<Projects>]
    def get_all_projects_using_get(opts = {})
      data, _status_code, _headers = get_all_projects_using_get_with_http_info(opts)
      return data
    end

    # getAllProjects
    # 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<Projects>, Fixnum, Hash)>] Array<Projects> data, response status code and response headers
    def get_all_projects_using_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: ProjectsresourceApi.get_all_projects_using_get ..."
      end
      # resource path
      local_var_path = "/api/projects"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<Projects>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ProjectsresourceApi#get_all_projects_using_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # getProjects
    # 
    # @param id id
    # @param [Hash] opts the optional parameters
    # @return [Projects]
    def get_projects_using_get(id, opts = {})
      data, _status_code, _headers = get_projects_using_get_with_http_info(id, opts)
      return data
    end

    # getProjects
    # 
    # @param id id
    # @param [Hash] opts the optional parameters
    # @return [Array<(Projects, Fixnum, Hash)>] Projects data, response status code and response headers
    def get_projects_using_get_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: ProjectsresourceApi.get_projects_using_get ..."
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling ProjectsresourceApi.get_projects_using_get"
      end
      # resource path
      local_var_path = "/api/projects/{id}".sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Projects')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ProjectsresourceApi#get_projects_using_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # updateProjects
    # 
    # @param projects projects
    # @param [Hash] opts the optional parameters
    # @return [Projects]
    def update_projects_using_put(projects, opts = {})
      data, _status_code, _headers = update_projects_using_put_with_http_info(projects, opts)
      return data
    end

    # updateProjects
    # 
    # @param projects projects
    # @param [Hash] opts the optional parameters
    # @return [Array<(Projects, Fixnum, Hash)>] Projects data, response status code and response headers
    def update_projects_using_put_with_http_info(projects, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: ProjectsresourceApi.update_projects_using_put ..."
      end
      # verify the required parameter 'projects' is set
      if @api_client.config.client_side_validation && projects.nil?
        fail ArgumentError, "Missing the required parameter 'projects' when calling ProjectsresourceApi.update_projects_using_put"
      end
      # resource path
      local_var_path = "/api/projects"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(projects)
      auth_names = []
      data, status_code, headers = @api_client.call_api(:PUT, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Projects')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ProjectsresourceApi#update_projects_using_put\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
