=begin
#gateway_timesheets API

#gateway_timesheets API documentation

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require "uri"

module SwaggerClient
  class UserresourceApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # createUser
    # 
    # @param user_dto userDTO
    # @param [Hash] opts the optional parameters
    # @return [User]
    def create_user_using_post(user_dto, opts = {})
      data, _status_code, _headers = create_user_using_post_with_http_info(user_dto, opts)
      return data
    end

    # createUser
    # 
    # @param user_dto userDTO
    # @param [Hash] opts the optional parameters
    # @return [Array<(User, Fixnum, Hash)>] User data, response status code and response headers
    def create_user_using_post_with_http_info(user_dto, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: UserresourceApi.create_user_using_post ..."
      end
      # verify the required parameter 'user_dto' is set
      if @api_client.config.client_side_validation && user_dto.nil?
        fail ArgumentError, "Missing the required parameter 'user_dto' when calling UserresourceApi.create_user_using_post"
      end
      # resource path
      local_var_path = "/api/users"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(user_dto)
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'User')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: UserresourceApi#create_user_using_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # deleteUser
    # 
    # @param login login
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def delete_user_using_delete(login, opts = {})
      delete_user_using_delete_with_http_info(login, opts)
      return nil
    end

    # deleteUser
    # 
    # @param login login
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def delete_user_using_delete_with_http_info(login, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: UserresourceApi.delete_user_using_delete ..."
      end
      # verify the required parameter 'login' is set
      if @api_client.config.client_side_validation && login.nil?
        fail ArgumentError, "Missing the required parameter 'login' when calling UserresourceApi.delete_user_using_delete"
      end
      # resource path
      local_var_path = "/api/users/{login}".sub('{' + 'login' + '}', login.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: UserresourceApi#delete_user_using_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # getAllUsers
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page Page number of the requested page
    # @option opts [Integer] :size Size of a page
    # @option opts [Array<String>] :sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
    # @return [Array<UserDTO>]
    def get_all_users_using_get(opts = {})
      data, _status_code, _headers = get_all_users_using_get_with_http_info(opts)
      return data
    end

    # getAllUsers
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page Page number of the requested page
    # @option opts [Integer] :size Size of a page
    # @option opts [Array<String>] :sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
    # @return [Array<(Array<UserDTO>, Fixnum, Hash)>] Array<UserDTO> data, response status code and response headers
    def get_all_users_using_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: UserresourceApi.get_all_users_using_get ..."
      end
      # resource path
      local_var_path = "/api/users"

      # query parameters
      query_params = {}
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'size'] = opts[:'size'] if !opts[:'size'].nil?
      query_params[:'sort'] = @api_client.build_collection_param(opts[:'sort'], :multi) if !opts[:'sort'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<UserDTO>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: UserresourceApi#get_all_users_using_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # getAuthorities
    # 
    # @param [Hash] opts the optional parameters
    # @return [Array<String>]
    def get_authorities_using_get(opts = {})
      data, _status_code, _headers = get_authorities_using_get_with_http_info(opts)
      return data
    end

    # getAuthorities
    # 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<String>, Fixnum, Hash)>] Array<String> data, response status code and response headers
    def get_authorities_using_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: UserresourceApi.get_authorities_using_get ..."
      end
      # resource path
      local_var_path = "/api/users/authorities"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<String>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: UserresourceApi#get_authorities_using_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # getUser
    # 
    # @param login login
    # @param [Hash] opts the optional parameters
    # @return [UserDTO]
    def get_user_using_get(login, opts = {})
      data, _status_code, _headers = get_user_using_get_with_http_info(login, opts)
      return data
    end

    # getUser
    # 
    # @param login login
    # @param [Hash] opts the optional parameters
    # @return [Array<(UserDTO, Fixnum, Hash)>] UserDTO data, response status code and response headers
    def get_user_using_get_with_http_info(login, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: UserresourceApi.get_user_using_get ..."
      end
      # verify the required parameter 'login' is set
      if @api_client.config.client_side_validation && login.nil?
        fail ArgumentError, "Missing the required parameter 'login' when calling UserresourceApi.get_user_using_get"
      end
      # resource path
      local_var_path = "/api/users/{login}".sub('{' + 'login' + '}', login.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'UserDTO')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: UserresourceApi#get_user_using_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # updateUser
    # 
    # @param user_dto userDTO
    # @param [Hash] opts the optional parameters
    # @return [UserDTO]
    def update_user_using_put(user_dto, opts = {})
      data, _status_code, _headers = update_user_using_put_with_http_info(user_dto, opts)
      return data
    end

    # updateUser
    # 
    # @param user_dto userDTO
    # @param [Hash] opts the optional parameters
    # @return [Array<(UserDTO, Fixnum, Hash)>] UserDTO data, response status code and response headers
    def update_user_using_put_with_http_info(user_dto, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: UserresourceApi.update_user_using_put ..."
      end
      # verify the required parameter 'user_dto' is set
      if @api_client.config.client_side_validation && user_dto.nil?
        fail ArgumentError, "Missing the required parameter 'user_dto' when calling UserresourceApi.update_user_using_put"
      end
      # resource path
      local_var_path = "/api/users"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(user_dto)
      auth_names = []
      data, status_code, headers = @api_client.call_api(:PUT, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'UserDTO')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: UserresourceApi#update_user_using_put\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
